spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lolDb?useSSL=false
    username: root
    password: q1w2e3r4
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    pl.jakubkozlowski.learning.firststeps.mapper.ChampionMapper: DEBUG

server:
  port: 8081
  context-path: /koziolek